In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [3]:
W1 = W2 = np.array([
    [10, 0.1],
    [0.25, 10]
])
W3 = np.array([10, 0.1])
b1 = b2 = np.array([[1], [1]])
b3 = 1
eta = 1

In [5]:
x = np.array([[0], [0]])

a1 = W1 @ x + b1
h1 = sigmoid(a1)
h1

array([[0.73105858],
       [0.73105858]])

In [7]:
a2 = W2 @ h1 + b2
h2 = sigmoid(a2)

In [12]:
a3 = W3 @ h2 + b3
h3 = sigmoid(a3)

In [13]:
h3

array([0.99998485])

In [14]:
def loss(y, yhat):
    return 0.5 * np.sum((y - yhat) ** 2)

loss(h3, [0])

0.4999848531371256

In [16]:
y = 0

In [17]:
y - h3

array([0.99998485])

In [19]:
a3

array([11.0976944])

In [20]:
h3

array([0.99998485])

In [21]:
h2

array([[0.99977149],
       [0.99979522]])

In [22]:
h21 = h2.ravel()[0]

In [27]:
(h3 - y) * h3 * (1 - h3 )

array([1.51465187e-05])

In [28]:
h2

array([[0.99977149],
       [0.99979522]])

In [26]:
a3

array([11.0976944])